validate/validate_test: Better error messages for unexpected JSON Schema errors
Instead of raising messages like:

  Error:  Not equal:
          expected: <nil>(<nil>)
          actual:
            *multierror.Error(*multierror.Error{Errors:[]error{(*errors.errorString)(0xc42037adc0)},
            ErrorFormat:(multierror.ErrorFormatFunc)(nil)})

raise messages like:

  * linux.rootfsPropagation: linux.rootfsPropagation must be one of
      the following: "private", "shared", "slave", "unbindable"

Signed-off-by: W. Trevor King <wking@tremily.us>