Makefile: replace TAP with TAPTOOL
Apparently, TAP is used by node-tap, so when it is used to specify a
path to node-tap, this results in a failure:

	$ make TAP=/path/to/node-tap localvalidation
	...
	Error: Environment variable TAP must be set to 0 or 1 only

Reported-by: David Gibson <david@gibson.dropbear.id.au>
Signed-off-by: Kir Kolyshkin <kolyshkin@gmail.com>