specerror: Pull runtime-spec-specific error handling into its own package
With 8f4d367 (error: Pull the RFC 2119 error representation into its
own package, 2017-07-28, #437), I'd created a package that was
completely independent of runtime-spec.  As I pointed out in that
commit message, this made it possible for image-tools and other
projects to reuse the generic RFC 2119 handling (which they care
about) without involving the runtime-spec-specific error enumeration
and such (which they don't care about).

In 25202126 (add stretchr/testify/assert pkgs; use rfc code in bundle
validation, 2017-08-29, #451), some runtime-spec-specific
functionality leaked into the error package.  I'd recommended keeping
configuration and runtime requirements separate [1], because you're
unlikely to be testing both of those at once.  But Liang wanted them
collected [2,3].  And the NewError and FindError utilities would be
the same regardless of target, so that's a good argument for keeping
them together.  This commit moves the runtime-spec-specific
functionality into a new package where both config and runtime
validators can share it, but where it won't pollute the generic RFC
2119 error package.

I've also changed NewError to take an error argument instead of a
string message, because creating an error from a string is easy
(e.g. with fmt.Errorf(...)), and using an error allows you to preserve
any additional structured information from a system error (e.g. as
returned by GetMounts).

[1]: https://github.com/opencontainers/runtime-tools/pull/451#discussion_r135844806
[2]: https://github.com/opencontainers/runtime-tools/pull/451#discussion_r135953382
[3]: https://github.com/opencontainers/runtime-tools/pull/451#issuecomment-325874457

Signed-off-by: W. Trevor King <wking@tremily.us>