README: Update to use 'make localvalidation'
Now that that is the only remaining runtime-validation approach.  I
ran the tests with runC 1.0.0-rc2, because using 1.0.0-rc3 raised:

  $ sudo make RUNTIME=~wking/bin/runc-1.0.0-rc3 localvalidation
  RUNTIME=/home/wking/bin/runc-1.0.0-rc3 go test -tags ""  -v github.com/opencontainers/runtime-tools/validation
  === RUN   TestValidateBasic
  json: cannot unmarshal array into Go value of type specs.LinuxCapabilities
  --- FAIL: TestValidateBasic (0.03s)
          validation_test.go:87: /home/wking/bin/runc-1.0.0-rc3 failed validation: exit status 1
  === RUN   TestValidateSysctls
  json: cannot unmarshal array into Go value of type specs.LinuxCapabilities
  --- FAIL: TestValidateSysctls (0.03s)
          validation_test.go:96: /home/wking/bin/runc-1.0.0-rc3 failed validation: exit status 1
  FAIL
  exit status 1
  FAIL    github.com/opencontainers/runtime-tools/validation      0.055s
  make: *** [Makefile:40: localvalidation] Error 1

because runtime-tools hasn't adjusted to the new seccomp config yet.

Signed-off-by: W. Trevor King <wking@tremily.us>