hack: drop -dev from runtime-spec version
There are a few tests that have this version hardcoded and fail if it
doesn't exist in various external places like,

--- FAIL: TestJSONSchema (2.41s)
    --- FAIL: TestJSONSchema/1_error_occurred:__*_Version_string_empty_Refer_to:_https://github.com/opencontainers/runtime-spec/blob/v1.0.1/config.md#specification-version (0.00s)
	Error Trace:	validate_test.go:267
	Error:      	Not equal:
	            	expected: "1 error occurred:\n\n* Version string empty\nRefer to: https://github.com/opencontainers/runtime-spec/blob/v1.0.1/config.md#specification-version"
	            	actual: "1 error occurred:\n\n* Version string empty\nRefer to: https://github.com/opencontainers/runtime-spec/blob/v1.0.1-dev/config.md#specification-version"

-- FAIL: TestGenerateValid (0.16s)
	generate_test.go:79: unexpected MUST error(s): 1 error occurred:

		* Could not read schema from HTTP, response status is 404 Not Found

because it seems to be looking for:

https://raw.githubusercontent.com/opencontainers/runtime-spec/v1.0.1-dev/schema/config-schema.json

These probably shouldn't be hard coded, but I'll let someone from the
project figure out how to solve it :)

Signed-off-by: Tycho Andersen <tycho@tycho.ws>