specerror: Add NewRFCError and NewRFCErrorOrPanic
So we don't have to dance around with casting to extract structured
information from NewError's returned error.

Signed-off-by: W. Trevor King <wking@tremily.us>